config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
	get 'about', to: 'products#about'

	post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
	delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

	root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, :description, :price_cents, presence: true
  validates :price_cents, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  has_one_attached :image

  def image_url
    Rails.application.routes.url_helpers.rails_representation_url(image.variant(resize: '100x100').processed)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController

	before_action :initialize_session
	before_action :increment_visit_count, only: %i[index about]
	before_action :load_cart

	def index
		@products = Product.all
	end

	def about
	end

	
	def add_to_cart
		id = params[:id].to_i
		session[:cart] << params[:id] unless session[:cart].include?(id)
		
		redirect_to root_path
	end
	
	
	def remove_from_cart	
		id = params[:id].to_i
		session[:cart].delete(id)

		redirect_to root_path
	end
	private
	
	def load_cart
		@cart = Product.find(session[:cart])
	end

	def initialize_session
		session[:visit_count] ||= 0 # Init
		session[:cart] ||= []
	end
	
	def increment_visit_count
		session[:visit_count] +=1 # Inc visit
		@visit_count = session[:visit_count]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeItUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<p>You have visited this site <%= pluralize @visit_count,'time' %>.</p>
    <%= yield %>
  </body>
</html>

app/views/products/about.html.erb
<h1>About Us</h1>

app/views/products/index.html.erb
<h1>All Products</h1>

<details>
	<summary>Shopping Cart</summary>	
	<% if @cart.empty? %>
		<p>No items in cart.</p>
	<% else %>
		<ul>
			<% @cart.each do |product| %>
		
				<li><%= product.name %> - <%= link_to 'remove from cart', remove_from_cart_path(product), method: :delete %></li>
			<% end %>
		</ul>
	<% end %>
</details>

<% @products.each do |product| %>
  <h3><%= product.name %></h3>
  <% if product.image.present? %>
    <p><%= image_tag product.image.variant(resize_to_limit: [100, 100]).processed  %></p>
  <% end %>
  <p>Price: <%= number_to_currency product.price_cents / 100.0 %></p>
  <p><%= product.description %></p>
	<% if @cart.include?(product) %>
		<p><%= button_to 'remove from cart', remove_from_cart_path(product), method: :delete %></p>
	<% else %>
		<p><%= link_to 'add to cart', add_to_cart_path(product.id), method: :post %></p>
	<% end %>
<% end %>